In [1]:
import numpy as np

In [13]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random([n,1])
    return A
    raise NotImplementedError


In [14]:
randomization(3)

array([[0.53415346],
       [0.82852436],
       [0.8130714 ]])

In [15]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    S=A+B
    return A,B,S
   
    raise NotImplementedError

In [16]:
operations(2, 2)

(array([[0.78090914, 0.84769036],
        [0.41716717, 0.91119477]]),
 array([[0.30651335, 0.93407496],
        [0.1461605 , 0.54231367]]),
 array([[1.08742249, 1.78176532],
        [0.56332767, 1.45350844]]))

In [18]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
   
   
    s = np.linalg.norm(A + B)
    return s
    raise NotImplementedError


In [20]:
 A = np.random.random([4,])

In [21]:
A

array([0.48069035, 0.78059289, 0.37779052, 0.86664175])

In [22]:
 B = np.random.random([4,])

In [23]:
 norm(A, B)

1.8818144196056785

In [24]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    return np.tanh(np.matmul(weights.transpose(), inputs))
    raise NotImplementedError


In [25]:
neural_network(np.random.random([2, 1]), np.random.random([2, 1]))

array([[0.72987588]])

In [31]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    if x<=y: 
        return x * y
    else  :
        return  x/y
    raise NotImplementedError

In [32]:
scalar_function(3, 2)

1.5

In [33]:
scalar_function(3, 3)

9

In [34]:
scalar_function(4, 2)

2.0

In [35]:
scalar_function(2, 5)

10

In [41]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    output = np.vectorize(scalar_function)
    return output(x,y)
    raise NotImplementedError

In [42]:
vector_function(3,2)

array(1.5)

In [43]:
vector_function(2,5)

array(10)

In [44]:
vector_function(3,3)

array(9)